Repository RTradeLtd/Temporal, pull requests merged in 2018-09, with the labels that each got.

#164 Ran scripts through shellcheck and manually corrected errors
  scripts/cluster_install.sh
  scripts/ethereum_install.sh
  scripts/ipfg.sh
  scripts/ipfs_cluster_monitor.sh
  scripts/temporal_manager.sh
Labels: enhancement

#165 adds test for user sign in, activates account on sign up.
  models/user.go
  models/user_test.go
Labels: enhancement

#169 CLI rework, version injection
  .github/CODE_OF_CONDUCT.md
  .gitignore
  .travis.yml
  Makefile
  README.md
  cmd/temporal/main.go
  cmd/temporal/utils.go
  cmd/temporal/utils_test.go
  config.json
  main.go
Labels: status:review

#172 CLI cross-compiled binaries, CI releases
  .gitignore
  .scripts/release.sh
  .travis.yml
  Makefile
Labels: status:review

#173 README project status and funding information updated
  README.md
Labels: status:review

#175 user model: updated password change to properly encode data in db
  models/user.go
Labels: status:review

#176 cli: improved app framework, nested commands
  cmd/temporal/app/app.go
  cmd/temporal/app/app_test.go
  cmd/temporal/app/cmd.go
  cmd/temporal/app/doc.go
  cmd/temporal/app/utils.go
  cmd/temporal/main.go
  cmd/temporal/utils.go
  cmd/temporal/utils_test.go
Labels: status:review

#178 scripts: changed cmd invocation from Temporal to temporal
  setup/scripts/temporal_manager.sh
  setup/scripts/temporal_service_monitoring.sh
Labels: status:review

#177 API Error Logging Cleanup
  api/api.go
  api/errors.go
  api/routes_account.go
  api/routes_database.go
  api/routes_frontend.go
  api/routes_ipns.go
  api/routes_mini.go
  api/routes_rtfs.go
  api/routes_rtfs_cluster.go
  api/routes_rtfsp.go
  api/utils.go
Labels: status:review

#180 Refined API Get IPFS Keys Call
  api/errors.go
  api/routes_account.go
Labels: status:review

#181 Configurable File Size Limit For Uploads
  api/errors.go
  api/routes_frontend.go
  api/routes_rtfs.go
  api/routes_rtfsp.go
  api/utils.go
  config/config.go
  config/config_test.go
  example.config.json
  test/config.json
Labels: status:review

#182 cli: create 'ipfs' sub-command
  cmd/temporal/main.go
  setup/scripts/temporal_manager.sh
Labels: status:review

#183 test: add rabbitmq to testenv, enable queue tests
  queue/queue_test.go
  test/docker-compose.yml
Labels: status:review

#184 CLI Cleanup
  cmd/temporal/main.go
  setup/scripts/temporal_manager.sh
Labels: status:review

#185 TEM-29: spin up 2x ipfs + ipfs-cluster nodes in testenv
  .travis.yml
  Makefile
  test/Dockerfile.ipfs
  test/docker-compose.yml
  test/ipfs/clusters/1/service.json
  test/ipfs/clusters/2/service.json
  test/ipfs/nodes/1/config
  test/ipfs/nodes/1/datastore_spec
  test/ipfs/nodes/1/version
  test/ipfs/nodes/2/config
  test/ipfs/nodes/2/datastore_spec
  test/ipfs/nodes/2/version
Labels: status:review

#187 script: update the command names for queue monitoring
  setup/scripts/temporal_service_monitoring.sh
Labels: status:review

#188 TEM-29: test ipfs functionality
  Makefile
  rtfs/rtfs.go
  rtfs/rtfs_test.go
  test/docker-compose.yml
Labels: status:review

#193 temporal_service_monitoring: fixed typo
  setup/scripts/temporal_service_monitoring.sh
Labels: status:review

#196 TEM-49: use gox to cross-compile releases
  .scripts/release.sh
  .travis.yml
Labels: status:review

#197 chore: add more lenient codecov config
  codecov.yml
Labels: status:review

#192 TEM-30: bootstrap postgres image in testenv
  Makefile
  api/api.go
  cmd/temporal/main.go
  database/database.go
  database/database_test.go
  test/docker-compose.yml
Labels: status:review

#194 TEM-46: temporal-api Docker image, api init refactors
  Dockerfile
  Makefile
  api/api.go
  cmd/temporal/main.go
  config/config.go
  config/config_test.go
  database/database.go
  example.config.json
  test/config.json
Labels: status:review

#195 TEM-31, TEM-47: docker-compose prod.yml
  .gitignore
  prod.yml
Labels: status:review

#198 readme: Add blurb about web interfaces
  README.md
Labels: status:review

#200 api: refactors
  Makefile
  api/api.go
  api/api_test.go
  api/context.go
  api/context_test.go
  api/log.go
  api/log_test.go
  api/routes_account.go
  api/routes_database.go
  api/routes_frontend.go
  api/routes_ipns.go
  api/routes_mini.go
  api/routes_rtfs.go
  api/routes_rtfs_cluster.go
  api/routes_rtfsp.go
  api/utils.go
  cmd/temporal/main.go
  config/config.go
  config/types.go
  database/database.go
  database/database_test.go
  test/config.json
Labels: status:review

#201 TEM-50: remove hardcoded home directory, enable user tests
  cmd/temporal/main.go
  mail/mail_test.go
  models/user_test.go
  queue/queue_test.go
Labels: status:review

#202 docker-compose config rename, doc updates
  README.md
  temporal.yml
Labels: status:review

#205 queue: change db connection method
  mail/mail.go
  queue/queue.go
Labels: priority:high, status:review

#206 Extract DCCD - Merge Before #2 Release Build
  dccd/dccd.go
  dccd/dccd_test.go
  dccd/utils.go
Labels: priority:high, status:review

#208 user: enable api access on acct signup
  models/user.go
  models/user_test.go
Labels: priority:rush

#207 Pkg/extract packages pt1
  Gopkg.lock
  Gopkg.toml
  api/api.go
  api/api_test.go
  cmd/temporal/app/app_test.go
  cmd/temporal/app/doc.go
  cmd/temporal/main.go
  config/config_test.go
  database/database.go
  database/database_test.go
  mail/mail.go
  mail/mail_test.go
  models/user_test.go
  queue/ipfs.go
  queue/ipfs_cluster.go
  queue/ipns.go
  queue/mail.go
  queue/queue.go
  setup/scripts/prom_node_exporter_install.sh
  vendor/github.com/RTradeLtd/cmd/.gitignore
  vendor/github.com/RTradeLtd/cmd/.travis.yml
  vendor/github.com/RTradeLtd/cmd/Gopkg.lock
  vendor/github.com/RTradeLtd/cmd/Gopkg.toml
  vendor/github.com/RTradeLtd/cmd/LICENSE
  vendor/github.com/RTradeLtd/cmd/README.md
  vendor/github.com/RTradeLtd/cmd/app.go
  vendor/github.com/RTradeLtd/cmd/cmd.go
  vendor/github.com/RTradeLtd/cmd/doc.go
  vendor/github.com/RTradeLtd/cmd/utils.go
  vendor/github.com/RTradeLtd/config/.gitignore
  vendor/github.com/RTradeLtd/config/.travis.yml
  vendor/github.com/RTradeLtd/config/LICENSE
  vendor/github.com/RTradeLtd/config/Makefile
  vendor/github.com/RTradeLtd/config/README.md
  vendor/github.com/RTradeLtd/config/config.go
  vendor/github.com/RTradeLtd/config/doc.go
  vendor/github.com/RTradeLtd/config/types.go
Labels: status:review

#210 readme: update media sections
  README.md
Labels: priority:low, status:review
