Repository RTradeLtd/Temporal, pull requests merged in 2018-11, with the labels that each got.

#240 Chore/linters
  .travis.yml
  cmd/temporal/main.go
  models/encrypted_test.go
Labels: status:review

#239 TNS PoC: TEM-68
  Gopkg.lock
  Gopkg.toml
  api/api.go
  api/routes_rtfs.go
  api/routes_tns.go
  cmd/temporal/main.go
  database/database.go
  eh/errors.go
  models/record.go
  models/tns.go
  models/user.go
  queue/database.go
  queue/queue.go
  queue/tns.go
  queue/types.go
  test/config.json
  tns/README.md
  tns/client.go
  tns/log.go
  tns/manager.go
  tns/tns_test.go
  tns/types.go
  tns/utils.go
  utils/cmc_test.go
  utils/ma_test.go
  utils/time_test.go
  utils/utils_test.go
  vendor/github.com/RTradeLtd/config/config.go
  vendor/github.com/RTradeLtd/config/types.go
Labels: status:review

#241 Satisfy Golint: TEM-121
  .travis.yml
  api/api.go
  api/middleware/api.go
  api/middleware/jwt.go
  api/routes_rtfs_cluster.go
  cmd/temporal/main.go
  database/database.go
  database/database_test.go
  mini/mini.go
  models/enterprise_upload.go
  models/ipfs_networks.go
  models/upload.go
  models/user.go
  queue/database.go
  queue/exchanges.go
  queue/ipfs.go
  queue/ipfs_cluster.go
  queue/ipns.go
  queue/log.go
  queue/log_test.go
  queue/mail.go
  queue/queue.go
  queue/tns.go
  queue/types.go
  queue/utils.go
  rtfs/keystore.go
  rtfs/utils.go
  rtfscluster/rtfs_cluster.go
  rtfscluster/rtfs_cluster_test.go
  rtfsp/rtfsp.go
  rtns/dlink/aws.go
  rtns/rtns.go
  tns/tns_test.go
  utils/multiaddr_validator.go
  utils/random.go
  utils/utils.go
Labels: status:review

#246 Clean Post Form Extraction
  api/routes_account.go
  api/routes_frontend.go
  api/routes_ipns.go
  api/routes_mini.go
  api/routes_payment.go
  api/routes_rtfs.go
  api/routes_rtfs_cluster.go
  api/routes_rtfsp.go
  api/routes_tns.go
  api/utils.go
Labels: status:wip

#249 docs: fix Medium link
  README.md
Labels: status:review

#247 IPFS Key Export: TEM-94
  Gopkg.lock
  Gopkg.toml
  api/api.go
  api/routes_account.go
  eh/errors.go
  rtfs/keystore.go
  rtfs/keystore_test.go
  vendor/github.com/NebulousLabs/entropy-mnemonics/.gitignore
  vendor/github.com/NebulousLabs/entropy-mnemonics/.travis.yml
  vendor/github.com/NebulousLabs/entropy-mnemonics/LICENSE
  vendor/github.com/NebulousLabs/entropy-mnemonics/README.md
  vendor/github.com/NebulousLabs/entropy-mnemonics/english.go
  vendor/github.com/NebulousLabs/entropy-mnemonics/german.go
  vendor/github.com/NebulousLabs/entropy-mnemonics/japanese.go
  vendor/github.com/NebulousLabs/entropy-mnemonics/mnemonics.go
Labels: status:review

#251 Forgot Password, Forgot Email, Reset Password: TEM-122
  api/api.go
  api/routes_account.go
  eh/errors.go
Labels: status:review

#250 Fix Private Network Integration
  Gopkg.lock
  Gopkg.toml
  api/api.go
  api/routes_account.go
  api/routes_rtfsp.go
  grpc-clients/orchestrator.go
  rtfs/keystore.go
  rtfs/rtfs.go
  test/config.json
  vendor/github.com/RTradeLtd/config/types.go
  vendor/github.com/RTradeLtd/grpc/ipfs-orchestrator/service.pb.go
  vendor/github.com/RTradeLtd/grpc/ipfs-orchestrator/service.proto
Labels: status:review

#252 Add Private Network Removal
  api/api.go
Labels: status:review

#253 Bug Fix: Private Network
  Gopkg.lock
  Gopkg.toml
  api/api.go
  api/routes_rtfsp.go
  vendor/github.com/RTradeLtd/database/models/ipfs_networks.go
  vendor/github.com/RTradeLtd/database/models/user.go
Labels: status:blocked

#242 api: add basic lens capabilities
  Gopkg.lock
  Gopkg.toml
  api/api.go
  api/routes_lens.go
  cmd/temporal/main.go
  eh/errors.go
  grpc-clients/lens.go
  vendor/github.com/RTradeLtd/config/types.go
  vendor/github.com/RTradeLtd/grpc/lens/request/request.pb.go
  vendor/github.com/RTradeLtd/grpc/lens/request/request.proto
  vendor/github.com/RTradeLtd/grpc/lens/response/response.pb.go
  vendor/github.com/RTradeLtd/grpc/lens/response/response.proto
  vendor/github.com/RTradeLtd/grpc/lens/service.pb.go
  vendor/github.com/RTradeLtd/grpc/lens/service.proto
  vendor/github.com/hsanjuan/go-libp2p-gostream/package.json
  vendor/github.com/jackpal/gateway/gateway_common.go
  vendor/github.com/jackpal/gateway/gateway_linux.go
  vendor/github.com/jackpal/gateway/gateway_windows.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_386.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
Labels: status:review

#257 Go Report Fix
  queue/ipfs.go
  queue/mail.go
  queue/queue.go
Labels: status:review

#260 docs: add subrepos to README, switch to Apache-2.0
  LICENSE
  README.md
Labels: status:review

#261 deps: update to kaas@v1.0.1, rebuild vendor
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/RTradeLtd/kaas/LICENSE
  vendor/github.com/ipfs/go-ipfs/commands/command.go
  vendor/github.com/ipfs/go-ipfs/commands/context.go
  vendor/github.com/ipfs/go-ipfs/commands/legacy/command.go
  vendor/github.com/ipfs/go-ipfs/commands/legacy/legacy.go
  vendor/github.com/ipfs/go-ipfs/commands/legacy/legacy_test.go
  vendor/github.com/ipfs/go-ipfs/commands/legacy/request.go
  vendor/github.com/ipfs/go-ipfs/commands/legacy/response.go
  vendor/github.com/ipfs/go-ipfs/commands/reqlog.go
  vendor/github.com/ipfs/go-ipfs/commands/response.go
  vendor/github.com/ipfs/go-ipfs/core/commands/cmdenv/env.go
  vendor/github.com/ipfs/go-ipfs/docs/datastores.md
  vendor/github.com/ipfs/go-ipfs/plugin/plugins/badgerds/badgerds.go
Labels: status:review

#263 hotfix: patch index request failure
  api/api.go
Labels: hotfix, priority:rush
